In [7]:
from numpy import random
import numpy as np

In [8]:
a= random.rand(30)
print(a)

[0.31715099 0.56786018 0.52478277 0.79559771 0.20244301 0.34064597
 0.20089111 0.03060463 0.09932569 0.5114338  0.94653467 0.86214566
 0.14530903 0.47240746 0.92513191 0.19269661 0.27725524 0.65297089
 0.20144086 0.22984923 0.20903214 0.78108583 0.81010906 0.90200585
 0.0934914  0.96263222 0.37718906 0.53808085 0.07610772 0.79008489]


In [13]:
batch_size=3
for x in range (0,len(a),batch_size):
    batch_num=a[x:x+batch_size]
    print(batch_num)

[0.31715099 0.56786018 0.52478277]
[0.79559771 0.20244301 0.34064597]
[0.20089111 0.03060463 0.09932569]
[0.5114338  0.94653467 0.86214566]
[0.14530903 0.47240746 0.92513191]
[0.19269661 0.27725524 0.65297089]
[0.20144086 0.22984923 0.20903214]
[0.78108583 0.81010906 0.90200585]
[0.0934914  0.96263222 0.37718906]
[0.53808085 0.07610772 0.79008489]
